final products = [
  {
    'id': '0',
    'title': 'Nike',
    'price': 44.52,
    'imageUrl': 'assets/images/nike.png',
    'company': 'Nike',
    'sizes': [7,8,9, 10, 11, 12,13],
  },
  {
    'id': '1',
    'title': 'Adidas',
    'price': 20.12,
    'imageUrl': 'assets/images/y.jpeg',
    'company': 'Adidas',
    'sizes': [7,8,9, 10, 11, 12],
  },
  {
    'id': '2',
    'title': 'RedTape',
    'price': 28.95,
    'imageUrl': 'assets/images/redtapee.jpg',
    'company': 'RedTape',
    'sizes':[7,8,9, 10, 11, 12],
  },
  {
    'id': '3',
    'title': 'Sketchers',
    'price': 420.69,
    'imageUrl': 'assets/images/sketchers.webp',
    'company': 'Sketchers',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Puma',
    'price': 420.69,
    'imageUrl': 'assets/images/puma.webp',
    'company': 'Puma',
    'sizes': [8, 9, 10],
  },
];
